services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  wchamara-api:
    container_name: wchamara-api
    image: wchamara/wchamara-customer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"

    depends_on:
      - db
    restart: unless-stopped
#    we can use this or env variable
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

volumes:
  db:

