services:
  db:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - db

volumes:
  db:

# create a network called spring-boot-example-network
networks:
  db:
    driver: bridge
